// Generated by Wrangler on Sun Dec 29 2024 02:15:42 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	NEWT_SPACE_UID: string;
	NEWT_CDN_API_TOKEN: string;
	NEWT_APP_UID: string;
	NEWT_MODEL_UID: string;
}
